### ISSUE TITLE
Error 'invalid license date(s)'

### ISSUE THREAD

**Issue by Diamant024** [qlik-oss/core-using-licenses#43]
When I call `licenseService/v1/licenses/allotments`, I get answer `{"errorMessage":"invalid license date(s)","errorType":"handler.forbiddenRequestError"}`. Qlik Core connected to this License Service doesn't work. How to fix it?

**Comment by wennmo** [comment]
The old `Beta` license has expired, but there is now a `Trial` license available.

https://core.qlik.com/licensing/

@Diamant024 Ok to close this issue?

**Comment by Diamant024** [comment]
@wennmo , thank you
