### ISSUE TITLE
Using licenses service in offline environment

### ISSUE THREAD

**Issue by IIIEII** [qlik-oss/core-using-licenses#72]
Hello,
Are there any way to use licences service in offline environment? For instance, generate lef and put it into some file?

**Comment by peol** [comment]
Hi, Qlik Core (by default) is online-licensed at this point. If you have a use case that would require offline-only access, feel free to reach out to us via either Slack or direct messages/email to discuss further details of your use case.

**Comment by wennmo** [comment]
Closing issue since the question has been answered.
